name: CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    test-macOS:
        name: macOS
        runs-on: macos-11.0
        steps:
            - name: Fetch TBB
              run: brew install tbb

            - name: Checkout HIP CPU Runtime
              uses: actions/checkout@v2

            - name: Build HIP CPU Runtime tests
              run: |
                cd ${{github.workspace}}
                mkdir build
                cd build
                cmake ../ -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_COMPILER=g++-10
                cmake --build ${{github.workspace}}/build --config RelWithDebInfo -j 3

            - name: Run Tests
              run: |
                cd ${{github.workspace}}/build
                ctest -C RelWithDebInfo --output-on-failure
    test-Ubuntu:
        if: false
        name: Ubuntu
        runs-on: ubuntu-20.04
        steps:
            - name: Fetch TBB
              run: sudo apt-get install libtbb-dev

            - name: Checkout HIP CPU Runtime
              uses: actions/checkout@v2

            - name: Build HIP CPU Runtime tests
              run: |
                cd ${{github.workspace}}
                mkdir build
                cd build
                cmake ../ -DCMAKE_BUILD_TYPE=RelWithDebInfo
                cmake --build ${{github.workspace}}/build --config RelWithDebInfo -j 3

            - name: Run Tests
              run: |
                cd ${{github.workspace}}/build
                ctest -C RelWithDebInfo --output-on-failure
    test-Windows:
        if: false
        name: Windows
        runs-on: windows-latest
        steps:
            - name: Checkout HIP CPU Runtime
              uses: actions/checkout@v2

            - name: Build HIP CPU Runtime tests
              run: |
                cd ${{github.workspace}}
                mkdir build
                cd build
                cmake ../ -DCMAKE_BUILD_TYPE=RelWithDebInfo
                cmake --build ${{github.workspace}}/build --config RelWithDebInfo

            - name: Run Tests
              run: |
                cd ${{github.workspace}}/build
                ctest -C RelWithDebInfo --output-on-failure